name: 🚀 Auto Release

on:
  push:
    branches:
      - main
      - new-feature-branch

jobs:
  instant-exit:
    runs-on: ubuntu-latest
    steps:
      - name: Auto release disabled
        run: echo "Auto release is temporarily disabled. Exit immediately."
